name: txtshow
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.19.4 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    text_composition:
        path: modules/text_composition
    sqflite: ^2.2.8+4
    sqflite_common_ffi: ^2.2.5
    get: ^4.6.5
    shared_preferences: ^2.2.2
    dio: 4.0.0
    connectivity: 3.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/bg/
        - assets/images/3.0x/
